#true: 使用Player.sendMessage()发送消息,false: 使用Player.sendActionBar()发送消息
use-message: true

items:
  - test-item:
      name: "Test Item"
      material: STONE
      lore:
        - "This is a test item"
        - "Click me!"
      enchantments:
        - minecraft:sharpness: 1
        - minecraft:unbreaking: 1
      attribute-modifiers:
        - "1":
            id: "axiumyu:test"
            amount: 1.0
            operation: "ADD_SCALAR"     #ADD_NUMBER, ADD_SCALAR, MULTIPLY_SCALAR_1;
            slot: "HAND"             #  ANY;MAINHAND;OFFHAND;HAND;FEET;LEGS;CHEST;HEAD;ARMOR;BODY;
            to: "MAX_HEALTH"        # https://purpurmc.org/javadoc/org/bukkit/attribute/Attribute.html
        - "2":
            id: "axiumyu:test2"
            amount: 1.3
            operation: "ADD_NUMBER"
            slot: "FEET"
            to: "ATTACK_SPEED"
      command:
        - "say Hello World"
        - "give %player% minecraft:stone 1"
      need-perm: false
      cooldown: 0